name: Tests & Linting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Node.js dependencies
        run: npm install

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      
      - name: Run lint
        run: npm run lint

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Node.js dependencies
        run: npm install

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r parser/requirements.txt
          pip install pytest ruff
      
      - name: Run src tests
        run: npm run test:src
      
      - name: Run parser tests
        run: npm run test:parser

      - name: Install playwright browsers
        run: npx playwright install --with-deps

      - name: Run webview tests
        run: npm run test:webview